"""Ubah Database

Revision ID: 401c09a57284
Revises: 
Create Date: 2023-08-27 11:50:46.879273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '401c09a57284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('User', 'Admin', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('video_table')
    op.drop_table('models')
    op.drop_table('image_table')
    op.drop_table('data_2_tangan')
    op.drop_table('data_1_tangan')
    op.drop_table('kamus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kamus',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('letter', mysql.CHAR(length=1), nullable=False),
    sa.Column('image_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('video_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_data_id'], ['image_table.id'], name='kamus_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_data_id'], ['video_table.id'], name='kamus_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_1_tangan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('class_label', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('huruf', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('image_data', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_2_tangan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('class_label', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('huruf', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('image_data', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('image_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('image_data', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('models',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('model_data', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('video_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('video_data', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Users')
    # ### end Alembic commands ###
